[[redirects]]
from="/playlists/*"
to="/.netlify/functions/playlists"
status=200

[[redirects]]
from="/twitch/*"
to="/.netlify/functions/twitch"
status=200

[[redirects]]
from="/get-stream-status-image/*"
to="/.netlify/functions/getStreamStatusImage"
status=200